# Generated by Django 2.0.3 on 2018-03-24 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usrname',
            new_name='username',
        ),
    ]
