# Generated by Django 2.0.3 on 2018-03-24 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20180324_1819'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
